<?php
namespace Zipkin;
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

$GLOBALS['Zipkin_zipkinCore_CONSTANTS'] = array();

$GLOBALS['Zipkin_zipkinCore_CONSTANTS']['CLIENT_SEND'] = "cs";

$GLOBALS['Zipkin_zipkinCore_CONSTANTS']['CLIENT_RECV'] = "cr";

$GLOBALS['Zipkin_zipkinCore_CONSTANTS']['SERVER_SEND'] = "ss";

$GLOBALS['Zipkin_zipkinCore_CONSTANTS']['SERVER_RECV'] = "sr";

?>
